#!/usr/bin/env bash

readonly AUTOGEN_BEGIN="# >>> AUTOGENERATED: DO NOT EDIT >>>"
readonly AUTOGEN_END="# <<< AUTOGENERATED: DO NOT EDIT <<<"

detect_target_user() {
  local candidate=""
  if [[ -n "${DBUS_BROKER_TARGET_USER:-}" ]] && [[ "${DBUS_BROKER_TARGET_USER:-}" != "root" ]] && id "${DBUS_BROKER_TARGET_USER:-}" >/dev/null 2>&1; then
    candidate="$DBUS_BROKER_TARGET_USER"
  elif [[ -n "${SUDO_USER:-}" ]] && [[ "${SUDO_USER:-}" != "root" ]] && id "${SUDO_USER:-}" >/dev/null 2>&1; then
    candidate="$SUDO_USER"
  else
    candidate="$(getent passwd | awk -F: '$3 >= 1000 && $3 < 60000 && $7 !~ /(false|nologin)$/ {print $1; exit}')"
  fi

  [[ -n "$candidate" ]] || die "could not determine invoking non-root user"
  DBUS_BROKER_TARGET_USER="$candidate"
  DBUS_BROKER_TARGET_HOME="$(getent passwd "$candidate" | awk -F: '{print $6}')"
  [[ -n "${DBUS_BROKER_TARGET_HOME:-}" ]] || die "could not determine home directory for '$candidate'"
}

detect_current_unit_fragments() {
  local user_fragment=""
  DBUS_BROKER_CURRENT_SYSTEM_FRAGMENT="$(systemctl show -p FragmentPath --value dbus.service 2>/dev/null || true)"
  DBUS_BROKER_CURRENT_SYSTEM_FRAGMENT="${DBUS_BROKER_CURRENT_SYSTEM_FRAGMENT:-unresolved}"

  if user_fragment="$(runuser -u "$DBUS_BROKER_TARGET_USER" -- systemctl --user show -p FragmentPath --value dbus.service 2>/dev/null)"; then
    DBUS_BROKER_USER_MANAGER_REACHABLE="yes"
    DBUS_BROKER_CURRENT_USER_FRAGMENT="${user_fragment:-unresolved}"
  else
    DBUS_BROKER_USER_MANAGER_REACHABLE="no"
    DBUS_BROKER_CURRENT_USER_FRAGMENT="unavailable"
  fi
}

write_autogen_block() {
  local env_file="$1"
  local temp_file block_file

  temp_file="$(mktemp "$(dirname "$env_file")/.env.tmp.XXXXXX")"
  block_file="$(mktemp "$(dirname "$env_file")/.env.block.XXXXXX")"

  cleanup_detect_temp_files() {
    rm -f -- "$temp_file" "$block_file"
  }
  trap cleanup_detect_temp_files RETURN

  cat >"$block_file" <<EOF
$AUTOGEN_BEGIN
DBUS_BROKER_TARGET_USER="$DBUS_BROKER_TARGET_USER"
DBUS_BROKER_TARGET_HOME="$DBUS_BROKER_TARGET_HOME"
DBUS_BROKER_CURRENT_SYSTEM_FRAGMENT="$DBUS_BROKER_CURRENT_SYSTEM_FRAGMENT"
DBUS_BROKER_CURRENT_USER_FRAGMENT="$DBUS_BROKER_CURRENT_USER_FRAGMENT"
DBUS_BROKER_USER_MANAGER_REACHABLE="$DBUS_BROKER_USER_MANAGER_REACHABLE"
$AUTOGEN_END
EOF

  awk -v begin="$AUTOGEN_BEGIN" -v end="$AUTOGEN_END" -v block="$block_file" '
    BEGIN {
      while ((getline line < block) > 0) {
        new_block[++count] = line
      }
      inserted = 0
      skip = 0
    }
    $0 == begin {
      for (i = 1; i <= count; i++) {
        print new_block[i]
      }
      inserted = 1
      skip = 1
      next
    }
    $0 == end {
      skip = 0
      next
    }
    !skip { print }
    END {
      if (!inserted) {
        for (i = 1; i <= count; i++) {
          print new_block[i]
        }
      }
    }
  ' "$env_file" >"$temp_file"

  run_cmd mv -- "$temp_file" "$env_file"
}

detect_install_context() {
  local env_file="$1"
  detect_target_user
  detect_current_unit_fragments
  write_autogen_block "$env_file"
  log_info "detected target user='$DBUS_BROKER_TARGET_USER' home='$DBUS_BROKER_TARGET_HOME'"
  log_info "current dbus.service fragments: system='${DBUS_BROKER_CURRENT_SYSTEM_FRAGMENT}', user='${DBUS_BROKER_CURRENT_USER_FRAGMENT}'"
}
