enable-ssh-support
pinentry-program /usr/bin/pinentry-gtk-2
disable-scdaemon
no-allow-external-cache
default-cache-ttl @KWALLET_SESSION_GPG_CACHE_TTL_SEC@
max-cache-ttl @KWALLET_SESSION_GPG_CACHE_TTL_SEC@
default-cache-ttl-ssh @KWALLET_SESSION_GPG_CACHE_TTL_SEC@
max-cache-ttl-ssh @KWALLET_SESSION_GPG_CACHE_TTL_SEC@
