font_family Noto Sans Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.5
cursor_shape beam
cursor_shape_unfocused hollow
cursor_beam_thickness 1.5
cursor_blink_interval 0.6
enable_audio_bell no
visual_bell_duration 0.0
copy_on_select clipboard
clear_selection_on_clipboard_loss yes
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
shell_integration enabled
confirm_os_window_close -1 count-background
scrollback_lines 30000
remember_window_size no
initial_window_width 960
initial_window_height 620
window_padding_width 12
wayland_titlebar_color background
active_border_color #6dc4ed
inactive_border_color #334155
url_color #7dd3fc
foreground #e5edf5
background #0f1720
selection_foreground #07131d
selection_background #94d2bd
cursor #f6bd60
cursor_text_color #07131d
color0 #1a2430
color1 #ef4444
color2 #22c55e
color3 #f59e0b
color4 #38bdf8
color5 #c084fc
color6 #2dd4bf
color7 #e2e8f0
color8 #475569
color9 #f87171
color10 #4ade80
color11 #fbbf24
color12 #7dd3fc
color13 #d8b4fe
color14 #5eead4
color15 #f8fafc
map alt+up send_text all \e[1;3A
map alt+down send_text all \e[1;3B
map alt+right send_text all \e[1;3C
map alt+left send_text all \e[1;3D
