#!/usr/bin/env bash

readonly AUTOGEN_BEGIN="# >>> AUTOGENERATED: DO NOT EDIT >>>"
readonly AUTOGEN_END="# <<< AUTOGENERATED: DO NOT EDIT <<<"

detect_target_user() {
  local candidate=""
  if [[ -n "${LABWC_TARGET_USER:-}" ]] && id "$LABWC_TARGET_USER" >/dev/null 2>&1; then
    candidate="$LABWC_TARGET_USER"
  elif [[ -n "${SUDO_USER:-}" ]] && [[ "${SUDO_USER:-}" != "root" ]] && id "${SUDO_USER:-}" >/dev/null 2>&1; then
    candidate="$SUDO_USER"
  else
    candidate="$(getent passwd | awk -F: '$3 >= 1000 && $3 < 60000 && $7 !~ /(false|nologin)$/ {print $1; exit}')"
  fi
  [[ -n "$candidate" ]] || die "could not determine target user"
  LABWC_TARGET_USER="$candidate"
  LABWC_TARGET_HOME="$(getent passwd "$candidate" | awk -F: '{print $6}')"
  [[ -n "$LABWC_TARGET_HOME" ]] || die "could not determine home for '$candidate'"
}

detect_gpu_vendor() {
  local gpu_info
  gpu_info="$(lspci -nn 2>/dev/null | grep -Ei 'vga|3d|display' || true)"
  gpu_info="${gpu_info,,}"
  LABWC_HAS_INTEL_GPU="no"
  LABWC_HAS_NVIDIA_GPU="no"
  LABWC_HAS_AMD_GPU="no"

  [[ "$gpu_info" == *intel* ]] && LABWC_HAS_INTEL_GPU="yes"
  [[ "$gpu_info" == *nvidia* ]] && LABWC_HAS_NVIDIA_GPU="yes"
  if [[ "$gpu_info" == *amd* || "$gpu_info" == *"advanced micro devices"* ]]; then
    LABWC_HAS_AMD_GPU="yes"
  fi
}

is_internal_connector() {
  case "$1" in
    eDP*|LVDS*|DSI*) return 0 ;;
    *) return 1 ;;
  esac
}

detect_outputs() {
  local entry status basename connector
  local -a connected=()
  for entry in /sys/class/drm/*/status; do
    [[ -e "$entry" ]] || continue
    status="$(<"$entry")"
    [[ "$status" == "connected" ]] || continue
    basename="${entry%/status}"
    basename="${basename##*/}"
    connector="${basename#*-}"
    connected+=("$connector")
  done

  LABWC_INTERNAL_OUTPUT=""
  LABWC_EXTERNAL_OUTPUT=""
  local output
  for output in "${connected[@]}"; do
    if is_internal_connector "$output"; then
      if [[ -z "$LABWC_INTERNAL_OUTPUT" ]]; then
        LABWC_INTERNAL_OUTPUT="$output"
      fi
    elif [[ -z "$LABWC_EXTERNAL_OUTPUT" ]]; then
      LABWC_EXTERNAL_OUTPUT="$output"
    fi
  done

  if [[ -n "$LABWC_INTERNAL_OUTPUT" && -n "$LABWC_EXTERNAL_OUTPUT" ]]; then
    LABWC_PRIMARY_OUTPUT="$LABWC_EXTERNAL_OUTPUT"
    LABWC_LAYOUT_MODE="internal-plus-external"
  elif [[ -n "$LABWC_EXTERNAL_OUTPUT" ]]; then
    LABWC_PRIMARY_OUTPUT="$LABWC_EXTERNAL_OUTPUT"
    LABWC_LAYOUT_MODE="external-only"
  else
    LABWC_PRIMARY_OUTPUT="$LABWC_INTERNAL_OUTPUT"
    LABWC_LAYOUT_MODE="internal-only"
  fi
  [[ -n "$LABWC_PRIMARY_OUTPUT" ]] || die "no connected outputs detected under /sys/class/drm"
  [[ -n "$LABWC_INTERNAL_OUTPUT" ]] || LABWC_INTERNAL_OUTPUT=""

  LABWC_INTERNAL_MODE="$(detect_connector_mode "$LABWC_INTERNAL_OUTPUT")"
  LABWC_EXTERNAL_MODE="$(detect_connector_mode "$LABWC_EXTERNAL_OUTPUT")"
  LABWC_INTERNAL_HZ="$(detect_connector_hz "$LABWC_INTERNAL_OUTPUT")"
  LABWC_EXTERNAL_HZ="$(detect_connector_hz "$LABWC_EXTERNAL_OUTPUT")"
  LABWC_EXTERNAL_120HZ_AVAILABLE=""
}

detect_connector_mode() {
  local connector="$1"
  [[ -n "$connector" ]] || return 0
  local mode_path=""
  for mode_path in /sys/class/drm/*-"$connector"/modes; do
    [[ -e "$mode_path" ]] || continue
    if [[ -s "$mode_path" ]]; then
      head -n 1 "$mode_path"
      return 0
    fi
  done
  return 0
}

detect_connector_hz() {
  local connector="$1"
  [[ -n "$connector" ]] || return 0
  printf '%s\n' "60"
}

write_autogen_block() {
  local env_file="$1"
  local runtime_env_path="$LABWC_TARGET_HOME/.config/debian-labwc/runtime.env"
  local temp_file block_file
  temp_file="$(mktemp)"
  block_file="$(mktemp)"

  cat >"$block_file" <<EOF
$AUTOGEN_BEGIN
LABWC_TARGET_USER="$LABWC_TARGET_USER"
LABWC_TARGET_HOME="$LABWC_TARGET_HOME"
LABWC_HAS_INTEL_GPU="$LABWC_HAS_INTEL_GPU"
LABWC_HAS_NVIDIA_GPU="$LABWC_HAS_NVIDIA_GPU"
LABWC_HAS_AMD_GPU="$LABWC_HAS_AMD_GPU"
LABWC_INTERNAL_OUTPUT="$LABWC_INTERNAL_OUTPUT"
LABWC_EXTERNAL_OUTPUT="$LABWC_EXTERNAL_OUTPUT"
LABWC_PRIMARY_OUTPUT="$LABWC_PRIMARY_OUTPUT"
LABWC_INTERNAL_MODE="$LABWC_INTERNAL_MODE"
LABWC_EXTERNAL_MODE="$LABWC_EXTERNAL_MODE"
LABWC_INTERNAL_HZ="$LABWC_INTERNAL_HZ"
LABWC_EXTERNAL_HZ="$LABWC_EXTERNAL_HZ"
LABWC_EXTERNAL_120HZ_AVAILABLE="$LABWC_EXTERNAL_120HZ_AVAILABLE"
LABWC_LAYOUT_MODE="$LABWC_LAYOUT_MODE"
$AUTOGEN_END
EOF

  awk -v begin="$AUTOGEN_BEGIN" -v end="$AUTOGEN_END" -v block="$block_file" '
    BEGIN {
      while ((getline line < block) > 0) {
        new_block[++count] = line
      }
      inserted = 0
      skip = 0
    }
    $0 == begin {
      for (i = 1; i <= count; i++) {
        print new_block[i]
      }
      inserted = 1
      skip = 1
      next
    }
    $0 == end {
      skip = 0
      next
    }
    !skip { print }
    END {
      if (!inserted) {
        for (i = 1; i <= count; i++) {
          print new_block[i]
        }
      }
    }
  ' "$env_file" >"$temp_file"

  mv -- "$temp_file" "$env_file"
  rm -f -- "$block_file"

  awk -v runtime_env="$runtime_env_path" -v repo_env="$env_file" '
    /^LABWC_RUNTIME_ENV_PATH=/ {$0 = "LABWC_RUNTIME_ENV_PATH=\"" runtime_env "\""}
    /^LABWC_REPO_ENV_PATH=/ {$0 = "LABWC_REPO_ENV_PATH=\"" repo_env "\""}
    {print}
  ' "$env_file" >"$temp_file"
  mv -- "$temp_file" "$env_file"
}

detect_hardware() {
  local env_file="$1"
  detect_target_user
  detect_gpu_vendor
  detect_outputs
  write_autogen_block "$env_file"
  log_info "detected user=$LABWC_TARGET_USER intel=$LABWC_HAS_INTEL_GPU nvidia=$LABWC_HAS_NVIDIA_GPU amd=$LABWC_HAS_AMD_GPU primary=$LABWC_PRIMARY_OUTPUT"
}
