#!/usr/bin/env bash

readonly AUTOGEN_BEGIN="# >>> AUTOGENERATED: DO NOT EDIT >>>"
readonly AUTOGEN_END="# <<< AUTOGENERATED: DO NOT EDIT <<<"

detect_target_user() {
  local candidate=""
  if [[ -n "${MAINTENANCE_TARGET_USER:-}" ]] && id "$MAINTENANCE_TARGET_USER" >/dev/null 2>&1; then
    candidate="$MAINTENANCE_TARGET_USER"
  elif [[ -n "${SUDO_USER:-}" ]] && [[ "${SUDO_USER:-}" != "root" ]] && id "${SUDO_USER:-}" >/dev/null 2>&1; then
    candidate="$SUDO_USER"
  else
    candidate="$(getent passwd | awk -F: '$3 >= 1000 && $3 < 60000 && $7 !~ /(false|nologin)$/ {print $1; exit}')"
  fi
  [[ -n "$candidate" ]] || die "could not determine maintenance target user"
  MAINTENANCE_TARGET_USER="$candidate"
  MAINTENANCE_TARGET_HOME="$(getent passwd "$candidate" | awk -F: '{print $6}')"
  [[ -n "$MAINTENANCE_TARGET_HOME" ]] || die "could not determine home for '$candidate'"
}

strip_findmnt_fsroot() {
  sed 's/\[[^]]*\]$//'
}

detect_grub_kernel_parameters() {
  local arg
  local grub_cmdline_linux=""
  local grub_cmdline_linux_default=""
  local grub_cmdline_combined=""

  if [[ -r /etc/default/grub ]]; then
    # shellcheck disable=SC1091
    source /etc/default/grub
    grub_cmdline_linux="${GRUB_CMDLINE_LINUX:-}"
    grub_cmdline_linux_default="${GRUB_CMDLINE_LINUX_DEFAULT:-}"
  fi

  if compgen -G '/etc/default/grub.d/*.cfg' >/dev/null 2>&1; then
    while IFS= read -r grub_dropin; do
      # shellcheck disable=SC1090
      source "$grub_dropin"
    done < <(find /etc/default/grub.d -maxdepth 1 -type f -name '*.cfg' | sort)
    grub_cmdline_linux="${GRUB_CMDLINE_LINUX:-$grub_cmdline_linux}"
    grub_cmdline_linux_default="${GRUB_CMDLINE_LINUX_DEFAULT:-$grub_cmdline_linux_default}"
  fi

  grub_cmdline_combined="${grub_cmdline_linux} ${grub_cmdline_linux_default}"
  grub_cmdline_combined="$(printf '%s\n' "$grub_cmdline_combined" | awk '{$1=$1; print}')"
  if [[ -z "$grub_cmdline_combined" ]] && [[ -r /proc/cmdline ]]; then
    grub_cmdline_combined="$(cat /proc/cmdline 2>/dev/null || true)"
  fi

  MAINTENANCE_CURRENT_KERNEL_PARAMETERS=""
  for arg in $grub_cmdline_combined; do
    case "$arg" in
      BOOT_IMAGE=*|root=*|rootfstype=*|rootflags=*|ro|rw|initrd=*) continue ;;
    esac
    if [[ -n "$MAINTENANCE_CURRENT_KERNEL_PARAMETERS" ]]; then
      MAINTENANCE_CURRENT_KERNEL_PARAMETERS+=" ${arg}"
    else
      MAINTENANCE_CURRENT_KERNEL_PARAMETERS="${arg}"
    fi
  done
}

detect_btrfs_layout() {
  local root_source_raw root_source_raw_fs root_source uuid device mountpoint device_uuid partition partition_uuid root_options_raw root_flags opt
  local -a devices=()
  local -a mountpoints=()
  local -a partitions=()

  root_source_raw="$(findmnt -rn -o SOURCE / || true)"
  root_source_raw_fs="$(findmnt -rn -o FSTYPE / || true)"
  [[ "$root_source_raw_fs" == "btrfs" ]] || die "root filesystem is '$root_source_raw_fs', but Timeshift is configured here for Btrfs only"
  root_source="$(printf '%s\n' "$root_source_raw" | strip_findmnt_fsroot)"
  [[ -n "$root_source" ]] || die "could not determine root Btrfs block device"
  root_options_raw="$(findmnt -rn -o OPTIONS / || true)"
  [[ -n "$root_options_raw" ]] || die "could not determine root Btrfs mount options"

  uuid="$(findmnt -rn -o UUID / 2>/dev/null || true)"
  if [[ -z "$uuid" ]]; then
    uuid="$(blkid -s UUID -o value "$root_source" 2>/dev/null || true)"
  fi
  [[ -n "$uuid" ]] || die "could not determine UUID for root Btrfs device '$root_source'"

  while IFS=$'\t' read -r device mountpoint device_uuid; do
    [[ -n "$device" ]] || continue
    [[ "$device_uuid" == "$uuid" ]] || continue
    devices+=("$device")
    mountpoints+=("$mountpoint")
  done < <(findmnt -rn -t btrfs -o SOURCE,TARGET,UUID --nofsroot | strip_findmnt_fsroot | sort -u)

  ((${#devices[@]} > 0)) || die "no mounted Btrfs block devices were detected"

  while IFS= read -r partition; do
    [[ -n "$partition" ]] || continue
    partition_uuid="$(blkid -s UUID -o value "$partition" 2>/dev/null || true)"
    [[ "$partition_uuid" == "$uuid" ]] || continue
    partitions+=("$partition")
  done < <(lsblk -rno PATH,TYPE,FSTYPE | awk '$2 == "part" && $3 == "btrfs" {print $1}' | sort -u)

  ((${#partitions[@]} > 0)) || die "no Btrfs partitions matching root UUID '$uuid' were detected via lsblk"

  root_flags=""
  IFS=',' read -r -a root_options_array <<<"$root_options_raw"
  for opt in "${root_options_array[@]}"; do
    case "$opt" in
      rw|ro|subvolid=*) continue ;;
      subvol=/*) opt="subvol=${opt#subvol=/}" ;;
    esac
    if [[ -n "$root_flags" ]]; then
      root_flags+=",${opt}"
    else
      root_flags="$opt"
    fi
  done
  [[ -n "$root_flags" ]] || die "could not derive Btrfs rootflags from '$root_options_raw'"

  MAINTENANCE_ROOT_BTRFS_SOURCE="$root_source"
  MAINTENANCE_ROOT_BTRFS_UUID="$uuid"
  MAINTENANCE_ROOT_BTRFS_KERNEL_FLAGS="rootfstype=btrfs rootflags=${root_flags}"
  MAINTENANCE_BTRFS_PARTITION_LIST="$(IFS=:; printf '%s' "${partitions[*]}")"
  MAINTENANCE_UNMOUNTED_BTRFS_PARTITION_LIST=""
  MAINTENANCE_BTRFS_PARTITION_COUNT="${#partitions[@]}"
  MAINTENANCE_BTRFS_DEVICE_LIST="$(IFS=:; printf '%s' "${devices[*]}")"
  MAINTENANCE_BTRFS_MOUNTPOINT_LIST="$(IFS=:; printf '%s' "${mountpoints[*]}")"
  MAINTENANCE_BTRFS_DEVICE_COUNT="${#devices[@]}"
}

write_autogen_block() {
  local env_file="$1"
  local temp_file block_file
  temp_file="$(dirname "$env_file")/.env.tmp.$$"
  block_file="$(dirname "$env_file")/.env.block.$$"

  cat >"$block_file" <<EOF
$AUTOGEN_BEGIN
MAINTENANCE_TARGET_USER="$MAINTENANCE_TARGET_USER"
MAINTENANCE_TARGET_HOME="$MAINTENANCE_TARGET_HOME"
MAINTENANCE_ROOT_BTRFS_SOURCE="$MAINTENANCE_ROOT_BTRFS_SOURCE"
MAINTENANCE_ROOT_BTRFS_UUID="$MAINTENANCE_ROOT_BTRFS_UUID"
MAINTENANCE_ROOT_BTRFS_KERNEL_FLAGS="$MAINTENANCE_ROOT_BTRFS_KERNEL_FLAGS"
MAINTENANCE_CURRENT_KERNEL_PARAMETERS="$MAINTENANCE_CURRENT_KERNEL_PARAMETERS"
MAINTENANCE_BTRFS_PARTITION_LIST="$MAINTENANCE_BTRFS_PARTITION_LIST"
MAINTENANCE_UNMOUNTED_BTRFS_PARTITION_LIST="$MAINTENANCE_UNMOUNTED_BTRFS_PARTITION_LIST"
MAINTENANCE_BTRFS_PARTITION_COUNT="$MAINTENANCE_BTRFS_PARTITION_COUNT"
MAINTENANCE_BTRFS_DEVICE_LIST="$MAINTENANCE_BTRFS_DEVICE_LIST"
MAINTENANCE_BTRFS_MOUNTPOINT_LIST="$MAINTENANCE_BTRFS_MOUNTPOINT_LIST"
MAINTENANCE_BTRFS_DEVICE_COUNT="$MAINTENANCE_BTRFS_DEVICE_COUNT"
$AUTOGEN_END
EOF

  awk -v begin="$AUTOGEN_BEGIN" -v end="$AUTOGEN_END" -v block="$block_file" '
    BEGIN {
      while ((getline line < block) > 0) {
        new_block[++count] = line
      }
      inserted = 0
      skip = 0
    }
    $0 == begin {
      for (i = 1; i <= count; i++) {
        print new_block[i]
      }
      inserted = 1
      skip = 1
      next
    }
    $0 == end {
      skip = 0
      next
    }
    !skip { print }
    END {
      if (!inserted) {
        for (i = 1; i <= count; i++) {
          print new_block[i]
        }
      }
    }
  ' "$env_file" >"$temp_file"

  run_cmd mv -- "$temp_file" "$env_file"
  run_cmd rm -f -- "$block_file"
}

detect_host_layout() {
  local env_file="$1"
  detect_target_user
  detect_btrfs_layout
  detect_grub_kernel_parameters
  write_autogen_block "$env_file"
  log_info "detected ${MAINTENANCE_BTRFS_PARTITION_COUNT} Btrfs partition(s) and ${MAINTENANCE_BTRFS_DEVICE_COUNT} mounted Btrfs device(s); root=${MAINTENANCE_ROOT_BTRFS_SOURCE}"
}
