#!/usr/bin/env bash

readonly AUTOGEN_BEGIN="# >>> AUTOGENERATED: DO NOT EDIT >>>"
readonly AUTOGEN_END="# <<< AUTOGENERATED: DO NOT EDIT <<<"

detect_target_user() {
  local candidate=""
  if [[ -n "${QBT_TARGET_USER:-}" ]] && [[ "${QBT_TARGET_USER:-}" != "root" ]] && id "${QBT_TARGET_USER:-}" >/dev/null 2>&1; then
    candidate="$QBT_TARGET_USER"
  elif [[ -n "${SUDO_USER:-}" ]] && [[ "${SUDO_USER:-}" != "root" ]] && id "${SUDO_USER:-}" >/dev/null 2>&1; then
    candidate="$SUDO_USER"
  else
    candidate="$(getent passwd | awk -F: '$3 >= 1000 && $3 < 60000 && $7 !~ /(false|nologin)$/ {print $1; exit}')"
  fi

  [[ -n "$candidate" ]] || die "could not determine the invoking non-root user for torrent access checks"
  QBT_TARGET_USER="$candidate"
  QBT_TARGET_HOME="$(getent passwd "$candidate" | awk -F: '{print $6}')"
  [[ -n "$QBT_TARGET_HOME" ]] || die "could not determine the home directory for '$candidate'"
}

capture_mount_metadata() {
  local path="$1"
  local prefix="$2"
  local target source fstype

  require_exact_mountpoint "$path"

  target="$(findmnt -rn -M "$path" -o TARGET)"
  source="$(findmnt -rn -M "$path" -o SOURCE)"
  fstype="$(findmnt -rn -M "$path" -o FSTYPE)"

  [[ "$target" == "$path" ]] || die "unexpected findmnt target for '$path': '$target'"
  [[ -n "$source" ]] || die "could not determine the mounted source for '$path'"
  [[ -n "$fstype" ]] || die "could not determine the mounted filesystem type for '$path'"

  printf -v "${prefix}_SOURCE" '%s' "$source"
  printf -v "${prefix}_FSTYPE" '%s' "$fstype"
}

write_autogen_block() {
  local env_file="$1"
  local temp_file block_file

  temp_file="$(mktemp "$(dirname "$env_file")/.env.tmp.XXXXXX")"
  block_file="$(mktemp "$(dirname "$env_file")/.env.block.XXXXXX")"

  cleanup_detect_temp_files() {
    rm -f -- "$temp_file" "$block_file"
  }
  trap cleanup_detect_temp_files RETURN

  cat >"$block_file" <<EOF
$AUTOGEN_BEGIN
QBT_TARGET_USER="$QBT_TARGET_USER"
QBT_TARGET_HOME="$QBT_TARGET_HOME"
QBT_TORRENTS_ROOT_SOURCE="$QBT_TORRENTS_ROOT_SOURCE"
QBT_TORRENTS_ROOT_FSTYPE="$QBT_TORRENTS_ROOT_FSTYPE"
QBT_TORRENTS_COMPLETE_SOURCE="$QBT_TORRENTS_COMPLETE_SOURCE"
QBT_TORRENTS_COMPLETE_FSTYPE="$QBT_TORRENTS_COMPLETE_FSTYPE"
QBT_TORRENTS_TEMP_SOURCE="$QBT_TORRENTS_TEMP_SOURCE"
QBT_TORRENTS_TEMP_FSTYPE="$QBT_TORRENTS_TEMP_FSTYPE"
$AUTOGEN_END
EOF

  awk -v begin="$AUTOGEN_BEGIN" -v end="$AUTOGEN_END" -v block="$block_file" '
    BEGIN {
      while ((getline line < block) > 0) {
        new_block[++count] = line
      }
      inserted = 0
      skip = 0
    }
    $0 == begin {
      for (i = 1; i <= count; i++) {
        print new_block[i]
      }
      inserted = 1
      skip = 1
      next
    }
    $0 == end {
      skip = 0
      next
    }
    !skip { print }
    END {
      if (!inserted) {
        for (i = 1; i <= count; i++) {
          print new_block[i]
        }
      }
    }
  ' "$env_file" >"$temp_file"

  run_cmd mv -- "$temp_file" "$env_file"
}

detect_install_context() {
  local env_file="$1"

  detect_target_user
  capture_mount_metadata "/data/mnt/g-drive/torrents" "QBT_TORRENTS_ROOT"
  capture_mount_metadata "/data/mnt/g-drive/torrents/complete" "QBT_TORRENTS_COMPLETE"
  capture_mount_metadata "/data/mnt/g-drive/torrents/temp" "QBT_TORRENTS_TEMP"
  write_autogen_block "$env_file"

  log_info "detected mounted torrent targets: user=${QBT_TARGET_USER}, root=${QBT_TORRENTS_ROOT_SOURCE}, complete=${QBT_TORRENTS_COMPLETE_SOURCE}, temp=${QBT_TORRENTS_TEMP_SOURCE}"
}
