[terminal]
vt = @GREETD_VT@
switch = true

[general]
source_profile = false

[default_session]
command = "/usr/bin/env HOME=/var/lib/greetd/greeter USER=greeter LOGNAME=greeter XDG_CACHE_HOME=/var/lib/greetd/greeter/.cache XDG_CONFIG_HOME=/var/lib/greetd/greeter/.config XDG_DATA_HOME=/var/lib/greetd/greeter/.local/share XDG_STATE_HOME=/var/lib/greetd/greeter/.local/state XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=labwc:wlroots XDG_SESSION_DESKTOP=labwc DESKTOP_SESSION=labwc GDK_BACKEND=wayland LIBSEAT_BACKEND=logind LABWC_UPDATE_ACTIVATION_ENV=0 WLR_NO_HARDWARE_CURSOR=1 XCURSOR_THEME=@XCURSOR_THEME@ XCURSOR_SIZE=@XCURSOR_SIZE@ /usr/bin/labwc -C /etc/labwc-greeter -S /usr/local/bin/labwc-greeter-regreet"
user = "greeter"
