[env]
XCURSOR_THEME = "@XCURSOR_THEME@"
XCURSOR_SIZE = "@XCURSOR_SIZE@"

[GTK]
cursor_theme_name = "@XCURSOR_THEME@"
cursor_blink = false
font_name = "Noto Sans 13"
theme_name = "Adwaita"

[commands]
reboot = ["/usr/sbin/reboot"]
poweroff = ["/usr/sbin/poweroff"]

[appearance]
greeting_msg = "Debian Labwc"

[widget.clock]
format = "%a %d %b  %H:%M"
resolution = "1s"
label_width = 220
