[background]
path = "@REGREET_BACKGROUND_PATH@"
fit = "@REGREET_BACKGROUND_FIT@"

[env]
XCURSOR_THEME = "@XCURSOR_THEME@"
XCURSOR_SIZE = "@XCURSOR_SIZE@"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "@XCURSOR_THEME@"
cursor_blink = true
font_name = "Noto Sans 14"
icon_theme_name = "Papirus-Dark"
theme_name = "Adwaita"

[commands]
reboot = ["loginctl", "reboot"]
poweroff = ["loginctl", "poweroff"]

[appearance]
greeting_msg = "Welcome to labwc"

[widget.clock]
format = "%a %H:%M"
resolution = "500ms"
label_width = 160
